{
 "title": "Flask Overview",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "RPS (total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Error rate (5xx) %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * ( sum(rate(http_requests_total{status=~\"5..\"}[5m])) / sum(rate(http_requests_total[5m])) )"
    }
   ]
  },
  {
   "title": "Latency p90 (by endpoint)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le, endpoint) (rate(http_request_duration_seconds_bucket[5m])))"
    }
   ]
  }
 ]
}